apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lbusybeagle
  namespace: argocd
spec:
  destination:
    name: 'in-cluster'
    namespace: 'busybeagle'
  source:
    path: manifests/busybeagle/overlays/danglindingo
    repoURL: 'https://github.com/ccrow42/busybeagle'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
  